AnimePictureETL/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AnimePictureETL.Models
{
    public class Artist
    {
        public virtual int ArtistId { get; set; }

        public virtual string Name { get; set; }

        public virtual ISet<Picture> Pictures { get; set; }
    }
}

AnimePictureETL/Models/Character.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AnimePictureETL.Models
{
    public class Character
    {
        public virtual int CharacterId { get; set; }

        public virtual string Name { get; set; }

        public virtual string FamilyName { get; set; }

        public virtual ISet<Picture> Pictures { get; set; }

        public virtual ISet<CharacterTag> CharacterTags { get; set; }

        public virtual string DanbooruName { get; set; }
    }
}

AnimePictureETL/Models/CharacterTag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AnimePictureETL.Models
{
    public class CharacterTag
    {
        public virtual long CharacterTagId { get; set; }

        public virtual Picture Picture { get; set; }

        public virtual Tag Tag { get; set; }

        public virtual Character Character { get; set; }
    }
}

AnimePictureETL/Models/Picture.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AnimePictureETL.Models
{
    public class Picture
    {
        public virtual long PictureId { get; set; }

        public virtual ISet<Character> Characters { get; set; }

        public virtual ISet<Artist> Artists { get; set; }

        public virtual ISet<Series> Series { get; set; }

        public virtual ISet<CharacterTag> CharacterTags { get; set; }

        public virtual DateTime UploadDate { get; set; }

        public virtual DateTime CreateDate { get; set; }

        public virtual long Size { get; set; }

        public virtual short Width { get; set; }

        public virtual short Height { get; set; }

        public virtual string Source { get; set; }

        public virtual string FileName { get; set; }

        public virtual string Md5Checksum { get; set; }

        public virtual Source Sources { get; set; }
    }
}

AnimePictureETL/Models/Series.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AnimePictureETL.Models
{
    public class Series
    {
        public virtual int SeriesId { get; set; }

        public virtual string Name { get; set; }

        public virtual ISet<Picture> Pictures { get; set; }
    }
}

AnimePictureETL/Models/Source.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AnimePictureETL.Models
{
    public class Source
    {
        public virtual long SourceId { get; set; }

        public virtual Picture Picture { get; set; }

        public virtual long PixivId { get; set; }

        public virtual long DanbooruId { get; set; }

        public virtual int MinitokyoId { get; set; }
    }
}

AnimePictureETL/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AnimePictureETL.Models
{
    public class Tag
    {
        public virtual int TagId { get; set; }

        public virtual string Name { get; set; }

        public virtual ISet<CharacterTag> CharacterTags { get; set; }
    }
}

AnimePictureETL/Controllers/BrowseController.cs
using AnimePictureETL.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AnimePictureETL.Controllers
{
    public class BrowseController : Controller
    {
        private IAnimeWorksService _animeWorksService;

        public BrowseController(IAnimeWorksService animeWorksService)
        {
            _animeWorksService = animeWorksService;
        }
        
        public ActionResult Index()
        {
            var picturesFirstPage = _animeWorksService.GetLastestPictures();
            return View(picturesFirstPage);
        }

        public ActionResult Search(string name, string familyName, string series, string artist)
        {
            var pictures = _animeWorksService.SearchPictures(name, familyName, series, artist);
            return View("Index", pictures);
        }
    }
}

AnimePictureETL/Controllers/HomeController.cs
using AnimePictureETL.ExtractedData;
using AnimePictureETL.Models;
using AnimePictureETL.Scrappers;
using AnimePictureETL.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AnimePictureETL.Extensions;
using AnimePictureETL.ExtractedData.Danbooru;
using System.Web.Routing;

namespace AnimePictureETL.Controllers
{
    public class HomeController : Controller
    {
        private IDanbooruService _danbooruService;

        private IAnimeWorksService _animeWorksService;

        public HomeController(IDanbooruService danbooruService, IAnimeWorksService animeWorksService)
        {
            _danbooruService = danbooruService;
            _animeWorksService = animeWorksService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public void DanbooruExtractTag(string tag)
        {
            string fileLink = Server.MapPath("~/Images");
            string configFilePath = Server.MapPath("~/Images/Config/danbooru_config.ini");
            ETL.DanbooruEtlProcess etl = new ETL.DanbooruEtlProcess(configFilePath, tag, fileLink);
            etl.Run();
        }

        public JsonResult DanbooruExtract(string id)
        {
            long danbooruId = Convert.ToInt64(id);
            var post = _danbooruService.ExtractPost(danbooruId);
            var postWithChanges = _danbooruService.GetSuggestedValuesForPost(post);

            string fileDest = Server.MapPath("~/Images/Tmp");
            string dest = fileDest + @"\" + postWithChanges.FileName;
            if (!System.IO.File.Exists(dest))
            {
                string source = DanbooruScrapper.DOWNLOAD_DEST + @"\" + postWithChanges.FileName;
                System.IO.File.Move(source, dest);
            }
            postWithChanges.FileName = string.Format("Images/Tmp/{0}", postWithChanges.FileName);
            return new JsonResult()
            {
                JsonRequestBehavior = JsonRequestBehavior.DenyGet,
                Data = postWithChanges
            };
        }

        public void SavePostWithChanges(PostChangesView data)
        {
            data.FileName = Path.GetFileName(data.FileName);
            string fileDest = Server.MapPath("~/Images");
            string tempLocation = Server.MapPath("~/Images/Tmp");
            string source = tempLocation + @"\" + data.FileName;
            string dest = fileDest + @"\" + data.FileName;
            if (!System.IO.File.Exists(dest))
            {
                System.IO.File.Move(source, dest);
            }
            data.FileName = string.Format("/Images/{0}", data.FileName); ;
            _danbooruService.Save(data);
        }
    }
}

AnimePictureETL/Controllers/PostController.cs
using AnimePictureETL.Repositories;
using AnimePictureETL.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AnimePictureETL.Controllers
{
    public class PostController : Controller
    {
        private IAnimeWorksService _animeWorksService;

        public PostController(IAnimeWorksService animeWorksService)
        {
            _animeWorksService = animeWorksService;
        }

        public ActionResult Index(long id)
        {
            var pic = _animeWorksService.GetPictureForView(id);
            if (pic != null)
            {
                Session["Picture"] = pic;
                return View();
            }
            else
            {
                return View("NoPost");
            }
        }
    }
}

AnimePictureETL/Views/Browse/Index.cshtml
@model  IList<AnimePictureETL.Models.Picture>
@{
    ViewBag.Title = "Index";
}

<h2>Browse</h2>

<div class="container">
    <div class="row" id="gallery">
        @foreach (var picture in Model)
        {
            <div class="col-md-4 col-sm-6 col-xs-12">
                <a href="/Post/Index?id=@picture.PictureId"><img src="@picture.FileName" class="img-responsive img-rounded"></a>
            </div>
        }
    </div>
</div>

AnimePictureETL/Views/Post/Index.cshtml
@{
    ViewBag.Title = "Index";
    var picture = (AnimePictureETL.Models.Picture)Session["Picture"];
}

<h2>Post @picture.PictureId</h2>

<div class="container">
    <div class="row">
        <div class="col-xs-2" id="tag-panel">
            <h4>Characters</h4>
            @foreach (var character in picture.Characters)
            {
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="character-box-@character.CharacterId">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse-@character.CharacterId" aria-expanded="true" aria-controls="collapse-@character.CharacterId">
                                @character.Name @character.FamilyName
                            </a>
                        </h4>
                    </div>
                    <div id="collapse-@character.CharacterId" class="panel-collapse collapse" role="tabpanel" aria-labelledby="character-box-@character.CharacterId">
                        <div class="panel-body">
                            @foreach(var tag in picture.CharacterTags)
                            {
                                if (tag.Character.DanbooruName == character.DanbooruName)
                                {
                                    <p>@tag.Tag.Name</p>
                                }
                            }
                        </div>
                    </div>
                </div>
            }
            <h4>Series</h4>
            <ul class="list-group">
                @foreach (var series in picture.Series)
                {
                    <li class="list-group-item">@series.Name</li>
                }
            </ul>
            <h4>Artists</h4>
            <ul class="list-group">
                @foreach (var artist in picture.Artists)
                {
                    <li class="list-group-item">@artist.Name</li>
                }
            </ul>
        </div>
        <div class="col-xs-10">
            <div class="row">
                <img src="@picture.FileName"  class="img-responsive">
            </div>
        </div>
    </div>
</div>

AnimePictureETL/Views/Post/NoPost.cshtml
@{
    ViewBag.Title = "NoPost";
}

<h2>No picture of such id.</h2>

AnimePictureETL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    @RenderSection("styles", required: false)
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AnimePictureETL", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Browse")">Browse</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>